######################################################################
# Automatically generated by qmake (3.0) Mon May 14 22:44:47 2018
######################################################################
QT += core
QT += gui
QT += widgets

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp

HEADERS += \
    gotocelldialog.h \
    ui_gotocelldialog.h
