######################################################################
# Automatically generated by qmake (3.0) Tue May 15 10:36:34 2018
######################################################################
QT += core
QT += gui
QT += widgets

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
