######################################################################
# Automatically generated by qmake (3.0) Tue May 15 15:25:08 2018
######################################################################

QT += core
QT += gui
QT += widgets

TEMPLATE = app
TARGET = sort
INCLUDEPATH += .

# Input
HEADERS += sortdialog.h \
    ui_sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp

